ydlidar_ros2_driver_node:
  ros__parameters:
    port: /dev/ttyUSB0
    frame_id: laser_frame
    ignore_array: ""
    baudrate: 512000
    lidar_type: 0
    device_type: 0
    isSingleChannel: false
    intensity: false
    intensity_bit: 0
    sample_rate: 20
    abnormal_check_count: 4
    fixed_resolution: false
    reversion: false
    inverted: false
    auto_reconnect: true
    support_motor_dtr: false
    angle_max: 180.0
    angle_min: -180.0
    range_max: 64.0
    range_min: 0.01
    frequency: 4.0
    invalid_range_is_inf: false
    debug: false
    qos_reliability: reliable # ADDED: To match subscribers (like RViz2/SLAM)